# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RunWidget/runWidget.ui'
#
# Created: Sun Apr 24 11:46:15 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_runWidget(object):
    def setupUi(self, runWidget):
        runWidget.setObjectName("runWidget")
        runWidget.resize(480, 320)
        self.fileLabel = QtGui.QLabel(runWidget)
        self.fileLabel.setGeometry(QtCore.QRect(10, 10, 461, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.fileLabel.setFont(font)
        self.fileLabel.setCursor(QtCore.Qt.UpArrowCursor)
        self.fileLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.fileLabel.setObjectName("fileLabel")
        self.BBOxGroup = QtGui.QGroupBox(runWidget)
        self.BBOxGroup.setEnabled(True)
        self.BBOxGroup.setGeometry(QtCore.QRect(240, 50, 230, 121))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BBOxGroup.setFont(font)
        self.BBOxGroup.setObjectName("BBOxGroup")
        self.xMinBBoxTxt = QtGui.QLineEdit(self.BBOxGroup)
        self.xMinBBoxTxt.setGeometry(QtCore.QRect(10, 30, 70, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.xMinBBoxTxt.setFont(font)
        self.xMinBBoxTxt.setReadOnly(True)
        self.xMinBBoxTxt.setObjectName("xMinBBoxTxt")
        self.yMinBBoxTxt = QtGui.QLineEdit(self.BBOxGroup)
        self.yMinBBoxTxt.setGeometry(QtCore.QRect(80, 30, 70, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.yMinBBoxTxt.setFont(font)
        self.yMinBBoxTxt.setReadOnly(True)
        self.yMinBBoxTxt.setObjectName("yMinBBoxTxt")
        self.zMinBBoxTxt = QtGui.QLineEdit(self.BBOxGroup)
        self.zMinBBoxTxt.setGeometry(QtCore.QRect(150, 30, 70, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.zMinBBoxTxt.setFont(font)
        self.zMinBBoxTxt.setReadOnly(True)
        self.zMinBBoxTxt.setObjectName("zMinBBoxTxt")
        self.xMaxBBoxTxt = QtGui.QLineEdit(self.BBOxGroup)
        self.xMaxBBoxTxt.setGeometry(QtCore.QRect(10, 70, 70, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.xMaxBBoxTxt.setFont(font)
        self.xMaxBBoxTxt.setReadOnly(True)
        self.xMaxBBoxTxt.setObjectName("xMaxBBoxTxt")
        self.yMaxBBoxTxt = QtGui.QLineEdit(self.BBOxGroup)
        self.yMaxBBoxTxt.setGeometry(QtCore.QRect(80, 70, 70, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.yMaxBBoxTxt.setFont(font)
        self.yMaxBBoxTxt.setReadOnly(True)
        self.yMaxBBoxTxt.setObjectName("yMaxBBoxTxt")
        self.zMaxBBoxTxt = QtGui.QLineEdit(self.BBOxGroup)
        self.zMaxBBoxTxt.setGeometry(QtCore.QRect(150, 70, 70, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.zMaxBBoxTxt.setFont(font)
        self.zMaxBBoxTxt.setReadOnly(True)
        self.zMaxBBoxTxt.setObjectName("zMaxBBoxTxt")
        self.estTimeGroup = QtGui.QGroupBox(runWidget)
        self.estTimeGroup.setGeometry(QtCore.QRect(240, 165, 230, 80))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.estTimeGroup.setFont(font)
        self.estTimeGroup.setObjectName("estTimeGroup")
        self.estTimeProgress = QtGui.QProgressBar(self.estTimeGroup)
        self.estTimeProgress.setGeometry(QtCore.QRect(10, 30, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.estTimeProgress.setFont(font)
        self.estTimeProgress.setProperty("value", 24)
        self.estTimeProgress.setObjectName("estTimeProgress")
        self.StopButton = QtGui.QPushButton(runWidget)
        self.StopButton.setGeometry(QtCore.QRect(4, 50, 231, 266))
        self.StopButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/stop_btn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.StopButton.setIcon(icon)
        self.StopButton.setIconSize(QtCore.QSize(200, 200))
        self.StopButton.setObjectName("StopButton")
        self.PauseButton = QtGui.QPushButton(runWidget)
        self.PauseButton.setGeometry(QtCore.QRect(240, 255, 231, 61))
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(27)
        font.setWeight(75)
        font.setBold(True)
        self.PauseButton.setFont(font)
        self.PauseButton.setObjectName("PauseButton")

        self.retranslateUi(runWidget)
        QtCore.QMetaObject.connectSlotsByName(runWidget)

    def retranslateUi(self, runWidget):
        runWidget.setWindowTitle(QtGui.QApplication.translate("runWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.fileLabel.setText(QtGui.QApplication.translate("runWidget", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.BBOxGroup.setTitle(QtGui.QApplication.translate("runWidget", "Bounding box", None, QtGui.QApplication.UnicodeUTF8))
        self.xMinBBoxTxt.setText(QtGui.QApplication.translate("runWidget", "1234", None, QtGui.QApplication.UnicodeUTF8))
        self.yMinBBoxTxt.setText(QtGui.QApplication.translate("runWidget", "1234", None, QtGui.QApplication.UnicodeUTF8))
        self.zMinBBoxTxt.setText(QtGui.QApplication.translate("runWidget", "1234", None, QtGui.QApplication.UnicodeUTF8))
        self.xMaxBBoxTxt.setText(QtGui.QApplication.translate("runWidget", "1234", None, QtGui.QApplication.UnicodeUTF8))
        self.yMaxBBoxTxt.setText(QtGui.QApplication.translate("runWidget", "1234", None, QtGui.QApplication.UnicodeUTF8))
        self.zMaxBBoxTxt.setText(QtGui.QApplication.translate("runWidget", "1234", None, QtGui.QApplication.UnicodeUTF8))
        self.estTimeGroup.setTitle(QtGui.QApplication.translate("runWidget", "Estimated time", None, QtGui.QApplication.UnicodeUTF8))
        self.estTimeProgress.setFormat(QtGui.QApplication.translate("runWidget", "00:00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.PauseButton.setText(QtGui.QApplication.translate("runWidget", "Pause", None, QtGui.QApplication.UnicodeUTF8))

