# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JogWidget/jogWidget_expand.ui'
#
# Created: Mon Apr 25 20:38:58 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_joyWidget(object):
    def setupUi(self, joyWidget):
        joyWidget.setObjectName("joyWidget")
        joyWidget.resize(480, 320)
        self.gridLayout = QtGui.QGridLayout(joyWidget)
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setHorizontalSpacing(3)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtGui.QWidget(joyWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fileLabel = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.fileLabel.setFont(font)
        self.fileLabel.setCursor(QtCore.Qt.UpArrowCursor)
        self.fileLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.fileLabel.setObjectName("fileLabel")
        self.horizontalLayout.addWidget(self.fileLabel)
        self.exitButton = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitButton.sizePolicy().hasHeightForWidth())
        self.exitButton.setSizePolicy(sizePolicy)
        self.exitButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/x_btn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitButton.setIcon(icon)
        self.exitButton.setIconSize(QtCore.QSize(24, 24))
        self.exitButton.setObjectName("exitButton")
        self.horizontalLayout.addWidget(self.exitButton)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 2)
        self.posGroup = QtGui.QGroupBox(joyWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.posGroup.setFont(font)
        self.posGroup.setObjectName("posGroup")
        self.gridLayout_2 = QtGui.QGridLayout(self.posGroup)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.xPosTxt = QtGui.QLineEdit(self.posGroup)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.xPosTxt.setFont(font)
        self.xPosTxt.setText("")
        self.xPosTxt.setReadOnly(True)
        self.xPosTxt.setObjectName("xPosTxt")
        self.gridLayout_2.addWidget(self.xPosTxt, 0, 0, 1, 1)
        self.yPosTxt = QtGui.QLineEdit(self.posGroup)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.yPosTxt.setFont(font)
        self.yPosTxt.setText("")
        self.yPosTxt.setReadOnly(True)
        self.yPosTxt.setObjectName("yPosTxt")
        self.gridLayout_2.addWidget(self.yPosTxt, 0, 1, 1, 1)
        self.zPosTxt = QtGui.QLineEdit(self.posGroup)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.zPosTxt.setFont(font)
        self.zPosTxt.setText("")
        self.zPosTxt.setReadOnly(True)
        self.zPosTxt.setObjectName("zPosTxt")
        self.gridLayout_2.addWidget(self.zPosTxt, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.posGroup, 1, 0, 1, 1)
        self.BBOxGroup = QtGui.QGroupBox(joyWidget)
        self.BBOxGroup.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BBOxGroup.setFont(font)
        self.BBOxGroup.setObjectName("BBOxGroup")
        self.gridLayout_3 = QtGui.QGridLayout(self.BBOxGroup)
        self.gridLayout_3.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.xMinBBoxTxt = QtGui.QLineEdit(self.BBOxGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xMinBBoxTxt.sizePolicy().hasHeightForWidth())
        self.xMinBBoxTxt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.xMinBBoxTxt.setFont(font)
        self.xMinBBoxTxt.setText("")
        self.xMinBBoxTxt.setReadOnly(True)
        self.xMinBBoxTxt.setObjectName("xMinBBoxTxt")
        self.gridLayout_3.addWidget(self.xMinBBoxTxt, 0, 0, 1, 1)
        self.yMinBBoxTxt = QtGui.QLineEdit(self.BBOxGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yMinBBoxTxt.sizePolicy().hasHeightForWidth())
        self.yMinBBoxTxt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.yMinBBoxTxt.setFont(font)
        self.yMinBBoxTxt.setText("")
        self.yMinBBoxTxt.setReadOnly(True)
        self.yMinBBoxTxt.setObjectName("yMinBBoxTxt")
        self.gridLayout_3.addWidget(self.yMinBBoxTxt, 0, 1, 1, 1)
        self.zMinBBoxTxt = QtGui.QLineEdit(self.BBOxGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zMinBBoxTxt.sizePolicy().hasHeightForWidth())
        self.zMinBBoxTxt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.zMinBBoxTxt.setFont(font)
        self.zMinBBoxTxt.setText("")
        self.zMinBBoxTxt.setReadOnly(True)
        self.zMinBBoxTxt.setObjectName("zMinBBoxTxt")
        self.gridLayout_3.addWidget(self.zMinBBoxTxt, 0, 2, 1, 1)
        self.xMaxBBoxTxt = QtGui.QLineEdit(self.BBOxGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xMaxBBoxTxt.sizePolicy().hasHeightForWidth())
        self.xMaxBBoxTxt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.xMaxBBoxTxt.setFont(font)
        self.xMaxBBoxTxt.setText("")
        self.xMaxBBoxTxt.setReadOnly(True)
        self.xMaxBBoxTxt.setObjectName("xMaxBBoxTxt")
        self.gridLayout_3.addWidget(self.xMaxBBoxTxt, 1, 0, 1, 1)
        self.yMaxBBoxTxt = QtGui.QLineEdit(self.BBOxGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yMaxBBoxTxt.sizePolicy().hasHeightForWidth())
        self.yMaxBBoxTxt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.yMaxBBoxTxt.setFont(font)
        self.yMaxBBoxTxt.setText("")
        self.yMaxBBoxTxt.setReadOnly(True)
        self.yMaxBBoxTxt.setObjectName("yMaxBBoxTxt")
        self.gridLayout_3.addWidget(self.yMaxBBoxTxt, 1, 1, 1, 1)
        self.zMaxBBoxTxt = QtGui.QLineEdit(self.BBOxGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zMaxBBoxTxt.sizePolicy().hasHeightForWidth())
        self.zMaxBBoxTxt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.zMaxBBoxTxt.setFont(font)
        self.zMaxBBoxTxt.setText("")
        self.zMaxBBoxTxt.setReadOnly(True)
        self.zMaxBBoxTxt.setObjectName("zMaxBBoxTxt")
        self.gridLayout_3.addWidget(self.zMaxBBoxTxt, 1, 2, 1, 1)
        self.gridLayout.addWidget(self.BBOxGroup, 1, 1, 2, 1)
        self.label = QtGui.QLabel(joyWidget)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 2, 1)
        self.estTimeGroup = QtGui.QGroupBox(joyWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.estTimeGroup.setFont(font)
        self.estTimeGroup.setObjectName("estTimeGroup")
        self.gridLayout_4 = QtGui.QGridLayout(self.estTimeGroup)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.estTimeTxt = QtGui.QLineEdit(self.estTimeGroup)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.estTimeTxt.setFont(font)
        self.estTimeTxt.setAlignment(QtCore.Qt.AlignCenter)
        self.estTimeTxt.setReadOnly(True)
        self.estTimeTxt.setObjectName("estTimeTxt")
        self.gridLayout_4.addWidget(self.estTimeTxt, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.estTimeGroup, 3, 1, 1, 1)
        self.RunButton = QtGui.QPushButton(joyWidget)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(27)
        font.setWeight(75)
        font.setBold(True)
        self.RunButton.setFont(font)
        self.RunButton.setObjectName("RunButton")
        self.gridLayout.addWidget(self.RunButton, 4, 0, 1, 1)
        self.LoadButton = QtGui.QPushButton(joyWidget)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(27)
        font.setWeight(75)
        font.setBold(True)
        self.LoadButton.setFont(font)
        self.LoadButton.setObjectName("LoadButton")
        self.gridLayout.addWidget(self.LoadButton, 4, 1, 1, 1)

        self.retranslateUi(joyWidget)
        QtCore.QMetaObject.connectSlotsByName(joyWidget)

    def retranslateUi(self, joyWidget):
        joyWidget.setWindowTitle(QtGui.QApplication.translate("joyWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.fileLabel.setText(QtGui.QApplication.translate("joyWidget", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.posGroup.setTitle(QtGui.QApplication.translate("joyWidget", "Current Pos", None, QtGui.QApplication.UnicodeUTF8))
        self.BBOxGroup.setTitle(QtGui.QApplication.translate("joyWidget", "Bounding box", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("joyWidget", "<html><head/><body><p>Joypad buttons:</p><p>%BTN_ZERO+1%: Set zero<br/>%BTN_ZEROZ+1%: Set Z=0<br/>%BTN_HOME+1%: Go to zero\n"
"<br/>%BTN_OK+1%: Run\n"
"<br/>%BTN_CANCEL+1%: Load</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.estTimeGroup.setTitle(QtGui.QApplication.translate("joyWidget", "Estimated time", None, QtGui.QApplication.UnicodeUTF8))
        self.estTimeTxt.setText(QtGui.QApplication.translate("joyWidget", "00:00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.RunButton.setText(QtGui.QApplication.translate("joyWidget", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.LoadButton.setText(QtGui.QApplication.translate("joyWidget", "Load", None, QtGui.QApplication.UnicodeUTF8))

